services:
  drupal:
    image: drupal:10-apache
    container_name: drupal
    restart: unless-stopped
    ports:
      - "${DRUPAL_HTTP_PORT:-8080}:80"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    networks:
      - projects-net
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:

networks:
  projects-net:
    external: true
    name: projects-net
