#!/usr/bin/env bash
#
# Remove generated secrets from DEPLOY_ROOT so generate-env-files.sh can recreate them.
#
# Deletes:
#   - <project>/.env — env files with passwords (generated from .env.example)
#   - .initial-credentials — plaintext credential summary
#   - pgadmin/servers.json — PostgreSQL password for pgAdmin auto-connect
#   - http-proxy/3proxy.cfg — proxy credentials (regenerated by generate-env-files.sh)
#
# Usage:
#   ./scripts/reset-env-secrets.sh --yes
#   DEPLOY_ROOT=/opt/projects ./scripts/reset-env-secrets.sh -y
#
# After reset:
#   DEPLOY_ROOT=/opt/projects ./scripts/generate-env-files.sh
#
# Note: Running containers may still use old passwords stored in Docker volumes
# (PostgreSQL, MinIO, Portainer admin, etc.). Run stack-down.sh first if you need
# a fully clean state before bringing the stack back up.
#
set -euo pipefail

DEPLOY_ROOT="${DEPLOY_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PROJECTS=(postgresql s3-storage freshrss static-server go-blog pgadmin portainer wg-easy http-proxy reverse-proxy pg-backup)

log() { printf '[reset-env-secrets] %s\n' "$*"; }
die() { log "ERROR: $*"; exit 1; }

confirm() {
  if [[ "${1:-}" == "-y" || "${1:-}" == "--yes" ]]; then
    return 0
  fi

  log "This will permanently delete secrets under ${DEPLOY_ROOT}:"
  log "  - .env files in ${#PROJECTS[@]} project directories"
  log "  - .initial-credentials, pgadmin/servers.json, http-proxy/3proxy.cfg"
  log ""
  log "Running services keep old passwords in Docker volumes until removed."
  printf 'Type "yes" to continue: '
  local answer
  read -r answer
  [[ "$answer" == "yes" ]] || die "Aborted"
}

remove_file() {
  local file="$1"
  if [[ -f "$file" ]]; then
    rm -f "$file"
    log "Removed ${file}"
  fi
}

main() {
  local project removed_any=0

  confirm "${1:-}"

  for project in "${PROJECTS[@]}"; do
    local env_file="${DEPLOY_ROOT}/${project}/.env"
    if [[ -f "$env_file" ]]; then
      rm -f "$env_file"
      log "Removed ${env_file}"
      removed_any=1
    fi
  done

  for file in \
    "${DEPLOY_ROOT}/.initial-credentials" \
    "${DEPLOY_ROOT}/pgadmin/servers.json" \
    "${DEPLOY_ROOT}/http-proxy/3proxy.cfg"
  do
    if [[ -f "$file" ]]; then
      rm -f "$file"
      log "Removed ${file}"
      removed_any=1
    fi
  done

  if [[ "$removed_any" -eq 0 ]]; then
    log "No secret files found — nothing to remove"
  else
    log "Done. Regenerate secrets with:"
    log "  DEPLOY_ROOT=${DEPLOY_ROOT} ./scripts/generate-env-files.sh"
  fi
}

main "$@"
