services:
  static-server:
    image: nginx:1.27.5-alpine
    container_name: static-server
    restart: unless-stopped
    ports:
      - "${STATIC_SERVER_HTTP_PORT:-8082}:80"
    volumes:
      - ./content:/usr/share/nginx/html:ro
    networks:
      - projects-net
    deploy:
      resources:
        limits:
          memory: 64M

networks:
  projects-net:
    external: true
    name: projects-net
