#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER ${DRUPAL_DB_USER} WITH PASSWORD '${DRUPAL_DB_PASSWORD}';
  CREATE DATABASE drupal OWNER ${DRUPAL_DB_USER};

  CREATE USER ${FRESHRSS_DB_USER} WITH PASSWORD '${FRESHRSS_DB_PASSWORD}';
  CREATE DATABASE freshrss OWNER ${FRESHRSS_DB_USER};
EOSQL
