#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER ${FRESHRSS_DB_USER} WITH PASSWORD '${FRESHRSS_DB_PASSWORD}';
  CREATE DATABASE freshrss OWNER ${FRESHRSS_DB_USER};

  CREATE USER ${GO_BLOG_DB_USER} WITH PASSWORD '${GO_BLOG_DB_PASSWORD}';
  CREATE DATABASE goblog OWNER ${GO_BLOG_DB_USER};
EOSQL
